on: 
  push:
    branches-ignore: [ 'v**.**.**' ]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Установка Rust
        uses: MatteoH2O1999/setup-rust@v1
        with: 
          channel: 1.75.0
      - name: Загрузка репозитория
        uses: actions/checkout@v4
      - name: Cборка
        run: cargo build --release
      - name: Отправка в Telegram (Сборка)
        uses: aps-m/telegram-notify-action@v1
        with:
          token: ${{secrets.TELEGRAMBOTTOKEN}}
          to: ${{secrets.TELEGRAMTARGETID}}
          document: 'target/release/skatworker_installation.dll'
      - name: Тестирование
        run: cargo test --lib --release tests
      - name: Отправка в Telegram (Успех)
        if: ${{ success() }}
        uses: aps-m/telegram-notify-action@v1
        with:
          token: ${{secrets.TELEGRAMBOTTOKEN}}
          to: ${{secrets.TELEGRAMTARGETID}}
          parse_mode: HTML
          message: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">Тест пройден успешно</a>
      - name: Отправка в Telegram (TimeOut)
        if: ${{ cancelled() }}
        uses: aps-m/telegram-notify-action@v1
        with:
          token: ${{secrets.TELEGRAMBOTTOKEN}}
          to: ${{secrets.TELEGRAMTARGETID}}
          parse_mode: HTML
          message: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">Сценарий отменён</a>
      - name: Отправка в Telegram (Не удача)
        if: ${{ failure() }}
        uses: aps-m/telegram-notify-action@v1
        with:
          token: ${{secrets.TELEGRAMBOTTOKEN}}
          to: ${{secrets.TELEGRAMTARGETID}}
          parse_mode: HTML
          message: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">Не удалось собрать библиотеку или тест провален</a>