on: 
  push:
    branches-ignore: [ 'v**.**.**' ]
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Установка Rust
        uses: MatteoH2O1999/setup-rust@v1
        with: 
          channel: 1.75.0-i686-pc-windows-msvc
      - name: Загрузка репозитория
        uses: actions/checkout@v4
      - name: Cборка
        run: cargo +1.75.0-i686-pc-windows-msvc build --release
      - name: Тестирование
        run: cargo test --release --lib
      - name: Перенос артефактов
        run: |
            mkdir artifacts
            move target\release\deps\*.exe artifacts
            move target\release\skatworker_installation.dll artifacts
      - name: Выгрузка артефактов
        uses: actions/upload-artifact@v4.6.2
        with:
          path: artifacts
        