on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Установка Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75.0
          override: true
          components: clippy, rustfmt
          
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          path-type: minimal
          install: >-
            mingw-w64-i686-toolchain

      - name: Загрузка репозитория
        uses: actions/checkout@v4

      - name: add target
        run: rustup target add i686-pc-windows-gnu

      - name: Cборка
        run: cargo build --release --target i686-pc-windows-gnu

      - name: Тест
        run: cargo test --release --lib --target i686-pc-windows-gnu

      - name: Выгрузка тестового дистрибутива
        uses: actions/upload-artifact@v4
        id: test
        with:
          name: test
          path: target\release\deps\*.exe          
          overwrite: true
          
      - name: Выгрузка библиотеки
        uses: actions/upload-artifact@v4
        with:
          name: lib
          path: target\release\skatworker_installation.dll
          overwrite: true
